// Generated by CoffeeScript 1.4.0
var TorrentDisplay;

document.ondrop = function() {
  return false;
};

document.ondragover = function() {
  return false;
};

(TorrentDisplay = function(viewer) {
  viewer.torrent = {};
  document.getElementById('body').ondrop = function(ev) {
    var fr, start;
    console.log('dropped');
    fr = new FileReader();
    start = 0;
    fr.onload = function(ev) {
      return start = new Date();
    };
    fr.onloadend = function(ev) {
      var torrent;
      torrent = bdecode(ev.target.result)[0];
      viewer.$apply(function() {
        viewer.baseName = torrent.info.name;
        return viewer.torrent = torrent;
      });
      console.log(viewer.torrent);
      return console.log("Parsed in " + (new Date() - start) + "ms");
    };
    fr.readAsBinaryString(ev.dataTransfer.files[0]);
    return false;
  };
  $('#body').on('dragenter', function(ev) {
    return console.log('Drag entered.');
  });
  $('#body').on('dragleave', function(ev) {
    return console.log('Drag left.');
  });
  return viewer.fileView = function(file) {
    var filePath, path, _i, _len, _ref;
    filePath = viewer.baseName;
    _ref = file.path;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      path = _ref[_i];
      filePath += '/' + path;
    }
    return "" + filePath;
  };
}).$inject = ['$scope'];
